--ozone-platform=wayland
--ozone-platform-hint=wayland
--top-chrome-touch-ui=disabled
--force-device-scale-factor=1
# Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
# AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiVideoDecoder,WaylandPerSurfaceScale,WaylandUiScale,BookmarksTreeView,DevToolsCssValueTracing,DevToolsPrivacyUI
--enable-gpu-rasterization
--enable-zero-copy
--canvas-oop-rasterization