[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[[colors.indexed_colors]]
color = "0x282828"
index = 18

[[colors.indexed_colors]]
color = "0x383838"
index = 19

[[colors.indexed_colors]]
color = "0xb8b8b8"
index = 20

[[colors.indexed_colors]]
color = "0xe8e8e8"
index = 21

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[colors.selection]
background = "0x575875"
text = "0xc0caf5"
