# Written by KalpaKavindu <kalpadevonline@gmail.com>


[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[[colors.indexed_colors]]
color = "0x282828"
index = 18

[[colors.indexed_colors]]
color = "0x383838"
index = 19

[[colors.indexed_colors]]
color = "0xb8b8b8"
index = 20

[[colors.indexed_colors]]
color = "0xe8e8e8"
index = 21

[colors.bright]
black = "0x414868"
blue = "0x7AA2F7"
cyan = "0x7DCFFF"
green = "0x73DACA"
magenta = "0xBB9AF7"
red = "0xF7768E"
white = "0xC0CAF5"
yellow = "0xE0AF68"

[colors.cursor]
cursor = "0xC0CAF5"
text = "CellBackground"

[colors.normal]
black = "0x414868"
blue = "0x7AA2F7"
cyan = "0x7DCFFF"
green = "0x73DACA"
magenta = "0xBB9AF7"
red = "0xF7768E"
white = "0xC0CAF5"
yellow = "0xE0AF68"

[colors.primary]
background = "0x1A1B2C"
foreground = "0xA9B1DC"

[colors.selection]
background = "0x28344A"
text = "0xc0caf5"
