# Written by KalpaKavindu <kalpadevonline@gmail.com>

wallpaper {
    monitor = eDP-1
    path = /home/kalpakavindu/Source/dotfiles/assets/wallpapers/anime-girl-with-blue-eyes-1920x1080.png
    fit_mode = cover
}
splash = false